'''
Enunciado:Hora de decidir! Os colaboradores da sua equipe foram sorteados para ganharem um console de última geração cada um por conta do bom desempenho que tiveram nos últimos projetos. Por uma questão de logística, porém, a empresa pede que todos os 5 membros da equipe recebam o mesmo aparelho.

Crie um algoritmo onde o usuário possa digitar o voto de cada um dos 5 membros da equipe e, ao final, exiba qual foi o console escolhido e com quantos votos.
As opções são: PLAYSTATION, XBOX e NINTENDO.
Obs: o código feito e feito para uso academico, e apenas utiliza funções aprendidas durante o curso da faculdade.
'''

primeiro_membro = str(input("Como primeiro membro,informe qual console deseja: P para playstation, X para xbox e N para nitendo "))
segundo_membro = str(input("Como segundo membro,informe qual console deseja: P para playstation, X para xbox e N para nitendo "))
terceiro_membro = str(input("Como terceiro membro,informe qual console deseja: P para playstation, X para xbox e N para nitendo "))
quarto_membro = str(input("Como quarto membro,informe qual console deseja: P para playstation, X para xbox e N para nitendo "))
quinto_membro = str(input("Como quinto membro,informe qual console deseja: P para playstation, X para xbox e N para nitendo "))

if primeiro_membro.upper() == "P" and segundo_membro.upper() == "P" and terceiro_membro.upper() == "P" or primeiro_membro.upper() == "P" and segundo_membro.upper() == "P" and quarto_membro.upper() == "P" or primeiro_membro.upper() == "P" and segundo_membro.upper() == "P" and quinto_membro.upper() == "P" or primeiro_membro.upper() == "P" and terceiro_membro.upper() == "P" and quarto_membro.upper() == "P" or primeiro_membro.upper() == "P" and terceiro_membro.upper() == "P" and quinto_membro.upper() == "P" or primeiro_membro.upper() == "P" and quarto_membro.upper() == "P" and quinto_membro.upper() == "P" or segundo_membro.upper() == "P" and terceiro_membro.upper() == "P" and quarto_membro.upper() == "P" or segundo_membro.upper() == "P" and terceiro_membro.upper() == "P" and quinto_membro.upper() == "P" or segundo_membro.upper() == "P" and quarto_membro.upper() == "P" and quinto_membro.upper() == "P" or terceiro_membro.upper() == "P" and quarto_membro.upper() == "P" and quinto_membro.upper() == "P":
    print("O console escolhido foi o playstation")
elif primeiro_membro.upper() == "X" and segundo_membro.upper() == "X" and terceiro_membro.upper() == "X" or primeiro_membro.upper() == "X" and segundo_membro.upper() == "X" and quarto_membro.upper() == "X" or primeiro_membro.upper() == "X" and segundo_membro.upper() == "X" and quinto_membro.upper() == "X" or primeiro_membro.upper() == "X" and terceiro_membro.upper() == "X" and quarto_membro.upper() == "X" or primeiro_membro.upper() == "X" and terceiro_membro.upper() == "X" and quinto_membro.upper() == "X" or primeiro_membro.upper() == "X" and quarto_membro.upper() == "X" and quinto_membro.upper() == "X" or segundo_membro.upper() == "X" and terceiro_membro.upper() == "X" and quarto_membro.upper() == "X" or segundo_membro.upper() == "X" and terceiro_membro.upper() == "X" and quinto_membro.upper() == "X" or segundo_membro.upper() == "X" and quarto_membro.upper() == "X" and quinto_membro.upper() == "X" or terceiro_membro.upper() == "X" and quarto_membro.upper() == "X" and quinto_membro.upper() == "X":
    print("O console escolhido foi o xbox")
elif primeiro_membro.upper() == "N" and segundo_membro.upper() == "N" and terceiro_membro.upper() == "N" or primeiro_membro.upper() == "N" and segundo_membro.upper() == "N" and quarto_membro.upper() == "N" or primeiro_membro.upper() == "N" and segundo_membro.upper() == "N" and quinto_membro.upper() == "N" or primeiro_membro.upper() == "N" and terceiro_membro.upper() == "N" and quarto_membro.upper() == "N" or primeiro_membro.upper() == "N" and terceiro_membro.upper() == "N" and quinto_membro.upper() == "N" or primeiro_membro.upper() == "N" and quarto_membro.upper() == "N" and quinto_membro.upper() == "N" or segundo_membro.upper() == "N" and terceiro_membro.upper() == "N" and quarto_membro.upper() == "N" or segundo_membro.upper() == "N" and terceiro_membro.upper() == "N" and quinto_membro.upper() == "N" or segundo_membro.upper() == "N" and quarto_membro.upper() == "N" and quinto_membro.upper() == "N" or terceiro_membro.upper() == "N" and quarto_membro.upper() == "N" and quinto_membro.upper() == "N":
    print("O console escolhido foi o nitendo")